### ISSUE TITLE
feat: 지도 페이지 구현 및 api 연결

### ISSUE THREAD

**Issue by ming0o** [CCD-Travel-Road/frontend#13]
### Issue
> 지도 메인 기능 구현

### ToDoList

- [x] 헤더 설정
- [x] 선택한 날짜 불러오기 & Day 계산
- [x] 검색창 구현

*** 
카카오맵 커스텀

- [ ] 해시태그 (AI 추천, 식당, 카페) 선택 시 해당 장소만 선별해 노출
- [ ] 장소를 코스에 등록
- [ ] 검색한 위치 근처 관광지 정보 추천 (한국관광공사 api)
- [ ] 장소 > 자세히 보기 > 구글 맵스 api 연결, 장소 정보 노출
- [ ] 코스 커스텀 완료 시 서버로 보내는 최적화 양식 찾아보기

### 추가 선택사항(Optional)

> 살려주세요 ..

**Comment by ming0o** [comment]
https://github.com/user-attachments/assets/6186aef3-51f9-43d1-bca8-4c9a9a1d19b1


! 살짝 버벅임 이슈
! 컴퓨터로 볼때와 핸드폰으로 볼 때의 비율이 살짝 차이가 남
! 핸드폰마다 다를거 같은데, 잘 모르겠네 .. ㅜ

**Comment by 76Dosu** [comment]
스크롤 이슈가 됐다 안됐다 한다느는 말??

**Comment by ming0o** [comment]
> 스크롤 이슈가 됐다 안됐다 한다느는 말??

ㅇㅇ ㅠ 스크롤이 컴이라 그런가 잘 안되는 느낌이네요 ..

**Comment by 76Dosu** [comment]
아
